### PR TITLE
Fix missing <unistd.h> header for sleep(3) definition

### PR DESCRIPTION
**Pull request by ColinIanKing**
Clean up build warning:
src/calibrate.c: In function ‘Calibrate’:
src/calibrate.c:32:9: warning: implicit declaration of function ‘sleep’ [-Wimplicit-function-declaration]
   32 |         sleep(1);

### CODE REVIEW

**Comment by hilldani** [comment]
Thanks! running the tests

**Comment by hilldani** [comment]
quick question what OS are you building on that shows this error? When we build in centos 7 I don't see this warning

**Comment by ColinIanKing** [comment]
I'm building this with debian breezy and sid.

**Review by hilldani — APPROVED** [review]
thanks!

**Pull request merged**
